pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: printenv
  displayName: Azure printenv

- bash: |
    set -ex
    sudo docker run linuxbrew/brew:latest /bin/bash -c "set -ex; git config --global user.name LinuxbrewTestBot;"
