trigger: none
pr:
  autoCancel: true
  branches:
    include:
    - '*'

jobs:
- job: BuildLinuxbrewCoreBottles
  timeoutInMinutes: 360
  pool:
    vmImage: 'ubuntu-16.04'
  container:
    image: homebrew/brew
    options: --user=0:0
  steps:
  - script: printenv
    displayName: Azure printenv
  - bash: |
      cd /home/linuxbrew/.linuxbrew/Homebrew
      git config --global user.name LinuxbrewTestBot
      git config --global user.email testbot@linuxbrew.sh
      git fetch origin --tags
      git reset --hard origin/master
    displayName: Setup Homebrew
  - bash: |
      rm -rf /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core
      cp -a $(Build.Repository.LocalPath) /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core
    displayName: Copy homebrew-core
  - bash: |
      cd /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core
      git checkout -b test
      git fetch origin "master:master" "pull/$SYSTEM_PULLREQUEST_PULLREQUESTNUMBER/head:pr"
      git checkout pr
    displayName: Setup taps and checkout
  - bash: |
      cd /tmp/bottles
      brew test-bot \
        --tap=homebrew/core \
        --bintray-org=linuxbrew \
        --git-name=LinuxbrewTestBot \
        --git-email=testbot@linuxbrew.sh \
        --keep-old
    displayName: Run test bot
    continueOnError: true
  - bash: |
      cp /tmp/bottles/*.bottle.* $(Build.ArtifactStagingDirectory)
    displayName: Copy json & bottle files
    condition: always()
    continueOnError: true
  - task: PublishPipelineArtifact@0
    inputs:
      artifactName: bottle-linux
      targetPath: $(Build.ArtifactStagingDirectory)
    displayName: Publish bottle-linux
    condition: always()

