name: Build bottles.

on:
  pull_request:
    paths:
      - 'Formula/*'

jobs:
  build-bottles:
    if: startsWith(github.event.pull_request.title, 'Merge') == false
    runs-on: ubuntu-latest
    container:
      image: homebrew/brew
    steps:
      - name: Checkout tap
        uses: actions/checkout@v2
      - name: Setup tap
        run: |
          rm -rf $(brew --repository ${{github.repository}})
          ln -s $GITHUB_WORKSPACE $(brew --repository ${{github.repository}})
      - name: Build bottles
        run: |
          mkdir ~/bottles
          cd ~/bottles
          brew test-bot \
            --tap=homebrew/core \
            --keep-old
      - name: Copy bottles
        id: copy_bottles
        if: always()
        run: |
          cp -a ~/bottles $GITHUB_WORKSPACE
          # Nested echo here to trim spaces from wc -l
          file_count=$(echo $(ls ~/bottles | wc -l))
          echo "::set-output name=file_count::$file_count"
      - name: Upload bottles
        if: steps.copy_bottles.outputs.file_count > 0
        uses: actions/upload-artifact@v1
        with:
          name: bottles
          path: bottles
