name: Build bottles

on: pull_request

jobs:
  build-bottles:
    runs-on: ubuntu-latest
    container:
      image: homebrew/brew
    env:
      HOMEBREW_NO_ANALYTICS: 1
      HOMEBREW_NO_AUTO_UPDATE: 1
    steps:
      - name: Checkout tap
        uses: actions/checkout@v2
      - name: Setup tap
        run: |
          rm -rf $(brew --repository ${{github.repository}})
          ln -s $GITHUB_WORKSPACE $(brew --repository ${{github.repository}})
      - name: Build bottles
        run: |
          mkdir ~/bottles
          cd ~/bottles
          brew test-bot --keep-old
          cp -a ~/bottles $GITHUB_WORKSPACE
      - name: Upload bottles
        if: always()
        uses: actions/upload-artifact@v1
        with:
          name: bottles
          path: bottles
