name: Build bottles from 'brew request-bottle' trigger.

on: repository_dispatch

jobs:
  bottling:
    runs-on: ubuntu-latest
    container:
      image: homebrew/brew
    steps:
      - name: Print details
        run: |
          echo formula=${{github.event.client_payload.formula}}
          echo sender=${{github.event.sender.login}}
          echo name=${{github.event.client_payload.name}}
          echo ignore-errors=${{github.event.client_payload.ignore_errors}}
      - name: Update tap
        run: |
          brew update-reset $(brew --repo ${{github.repository}})
      - name: Build bottles
        run: |
          mkdir ~/bottles
          cd ~/bottles
          brew test-bot \
            --tap=homebrew/core \
            --keep-old \
            ${{github.event.client_payload.formula}}
      - name: Upload bottles
        env:
          HOMEBREW_BINTRAY_USER: LinuxbrewTestBot
          HOMEBREW_BINTRAY_KEY: ${{secrets.HOMEBREW_BINTRAY_KEY}}
        if: success() || github.event.client_payload.ignore_errors
        run: |
          cd ~/bottles
          brew test-bot \
            --tap=homebrew/core \
            --bintray-org=linuxbrew \
            --ci-upload \
            --publish \
            --keep-old \
            ${{github.event.client_payload.formula}}
      - name: Push bottles
        env:
          GIT_COMMITTER_NAME: ${{github.event.client_payload.name}}
          GIT_COMMITTER_EMAIL: ${{github.event.client_payload.email}}
        if: success() || github.event.client_payload.ignore_errors
        run: |
          cd $(brew --repo ${{github.repository}})
          git commit --amend --no-edit
          git show --pretty=fuller
          git fetch
          git rebase origin/master
          git fetch
          git rebase origin/master
          git push https://x-access-token:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}} master
