name: Request bottles after upstream merge.

on:
  push:
    branches:
      - master
    paths:
      - 'Formula/*'

jobs:
  request-bottles:
    if: startsWith(github.event.head_commit.message, 'Merge') == true
    runs-on: ubuntu-latest
    container:
      image: homebrew/brew
    steps:
      - name: Tap linux-dev
        run: |
          brew tap homebrew/linux-dev
      - name: Update tap
        run: |
          brew update-reset $(brew --repo ${{github.repository}})
      - name: Request bottles
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{secrets.HOMEBREW_GITHUB_API_TOKEN}}
          GIT_COMMITTER_NAME: ${{github.event.pusher.name}}
          GIT_COMMITTER_EMAIL: ${{github.event.pusher.email}}
        run: |
          brew find-formulae-to-bottle | xargs -n1 brew request-bottle
