name: Start VM
on:
  pull_request_target:
    paths:
      - "Formula/**"
      - "!Formula/patchelf.rb"
      - "!Formula/binutils.rb"
jobs:
  start_vm:
    if: github.repository == 'Homebrew/linuxbrew-core' && contains(github.event.pull_request.labels.*.name, 'self-hosted-ci')
    runs-on: ubuntu-latest
    steps:
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - name: Start VM
        id: runner
        run: |
          retries=10000
          for ((i=0; i<retries; i++)); do
              echo "Checking for available VM"
              runner=$(gcloud compute instances list --filter=TERMINATED --format="value(name)" | head -n 1)
              [[ ! -z "$runner" ]] && break

              echo "No instance found, waiting 60 seconds (attempt $i/$retries)"
              sleep 60
          done
          # Start the VM
          gcloud compute instances start --zone=europe-west1-b $runner
          echo "::set-output name=runner::$runner"
      - name: Label pull request
        uses: Homebrew/actions/label-pull-requests@master
        if: always()
        with:
          token: ${{secrets.HOMEBREW_GITHUB_API_TOKEN}}
          def: |
            [
                {
                    "label": "${{steps.runner.outputs.runner}}",
                    "path": "Formula/.+"
                }
            ]
