name: Upload bottles.

on:
  push:
    branches:
      - master
    paths:
      - 'Formula/*'

jobs:
  upload-bottles:
    if: startsWith(github.event.head_commit.message, 'Merge') == false && github.event.pusher.name != 'BrewTestBot'
    runs-on: ubuntu-latest
    container:
      image: homebrew/brew
    steps:
      - name: Get artifact data
        uses: actions/github-script@0.8.0
        id: artifact
        with:
          result-encoding: string
          script: |
            const prs = await github.repos.listPullRequestsAssociatedWithCommit({
              owner: context.repo.owner,
              repo: context.repo.repo,
              commit_sha: context.payload.head_commit.id
            })
            console.log(prs.data.length + " prs")
            if (prs.data.length === 0) {
              console.log("No pull requests are associated with this merge commit.")
              return 0
            }
            const pr = prs.data[0]
            console.log("first pr head ref=" + pr.head.ref)

            const runs = await github.actions.listWorkflowRuns({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: "build-bottles.yml",
              branch: pr.head.ref
              })
            console.log(runs.data.total_count + " runs")
            if (runs.data.total_count === 0) {
              console.log("No workflow runs are associated with this pull request.")
              return 0
            }

            const artifacts = await github.actions.listWorkflowRunArtifacts({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: runs.data.workflow_runs[0].id
              })
            console.log(artifacts.data.total_count + " artifacts")
            if (artifacts.data.total_count === 0) {
              console.log("No artifacts were uploaded for this workflow run.")
              return 0
            }
            console.log("Artifact <" + artifacts.data.artifacts[0].archive_download_url + ">")
            return artifacts.data.artifacts[0].id
      - name: Install unzip
        if: steps.artifact.outputs.result != 0
        env:
          HOMEBREW_NO_ANALYTICS: 1
        run: |
          brew install unzip
      - name: Download bottles
        if: steps.artifact.outputs.result != 0
        run: |
          set -eu
          mkdir ~/bottles
          cd ~/bottles
          artifact_id=${{steps.artifact.outputs.result}}
          echo "artifact_id=$artifact_id"
          curl -L -o bottles.zip "https://${{secrets.HOMEBREW_GITHUB_API_TOKEN}}@api.github.com/repos/${{github.repository}}/actions/artifacts/$artifact_id/zip"
          file bottles.zip
          unzip bottles.zip
      - name: Upload and publish bottles
        env:
          HOMEBREW_BINTRAY_USER: LinuxbrewTestBot
          HOMEBREW_BINTRAY_KEY: ${{secrets.HOMEBREW_BINTRAY_KEY}}
        if: steps.artifact.outputs.result != 0
        run: |
          cd ~/bottles
          brew update-reset $(brew --repo ${{github.repository}})
          brew test-bot \
            --tap=homebrew/core \
            --bintray-org=linuxbrew \
            --ci-upload \
            --publish \
            --keep-old
      - name: Push bottle commit
        env:
          GIT_COMMITTER_NAME: ${{github.event.pusher.name}}
          GIT_COMMITTER_EMAIL: ${{github.event.pusher.email}}
        if: steps.artifact.outputs.result != 0
        run: |
          cd $(brew --repo ${{github.repository}})
          git commit --amend --no-edit
          git show --pretty=fuller
          for try in $(seq 5); do
            git fetch
            git rebase origin/master
            if git push https://x-access-token:${{secrets.HOMEBREW_GITHUB_API_TOKEN}}@github.com/${{github.repository}} master; then
              exit 0
            else
              sleep $(shuf -i 3-10 -n 1)
            fi
          done
          exit 1
      - name: Post comment on failure
        if: failure()
        uses: actions/github-script@0.8.0
        with:
          script: |
            const run_id = process.env.GITHUB_RUN_ID
            const actor = process.env.GITHUB_ACTOR
            console.log("run_id=" + run_id)
            console.log("actor=" + actor)

            const prs = await github.repos.listPullRequestsAssociatedWithCommit({
              owner: context.repo.owner,
              repo: context.repo.repo,
              commit_sha: context.payload.head_commit.id
            })
            console.log(prs.data.length + " prs")
            if (prs.data.length === 0) {
              console.log("No pull requests are associated with this merge commit.")
              return 0
            }
            const pr = prs.data[0]

            console.log("pr=" + pr.number)

            const repository = context.repo.owner + '/' + context.repo.repo
            const url = 'https://github.com/' + repository + '/actions/runs/' + run_id

            github.issues.createComment({
              issue_number: pr.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '@' + actor + ' upload bottles job failed: ' + url
            })
