name: Upload bottles.

on:
  push:
    branches:
      - master
    paths:
      - 'Formula/*'

jobs:
  upload-bottles:
    if: startsWith(github.event.head_commit.message, 'Merge') == false && github.event.pusher.name != 'BrewTestBot'
    runs-on: ubuntu-latest
    container:
      image: homebrew/brew
    steps:
      - name: Get PR associated with commit
        uses: jwalton/gh-find-current-pr@v1.0.2
        id: pr
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
      - name: Download bottles
        uses: dawidd6/action-download-artifact@v1.1.0
        if: steps.pr.outputs.number != ''
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          pr: ${{steps.pr.outputs.number}}
          workflow: build-bottles.yml
          name: bottles
      - name: Upload and publish bottles
        env:
          HOMEBREW_BINTRAY_USER: LinuxbrewTestBot
          HOMEBREW_BINTRAY_KEY: ${{secrets.HOMEBREW_BINTRAY_KEY}}
        if: steps.pr.outputs.number != ''
        run: |
          brew update-reset $(brew --repo ${{github.repository}})
          brew test-bot \
            --tap=homebrew/core \
            --bintray-org=linuxbrew \
            --ci-upload \
            --publish \
            --keep-old
      - name: Push bottle commit
        env:
          GIT_COMMITTER_NAME: ${{github.event.pusher.name}}
          GIT_COMMITTER_EMAIL: ${{github.event.pusher.email}}
        if: steps.pr.outputs.number != ''
        run: |
          cd $(brew --repo ${{github.repository}})
          git commit --amend --no-edit
          git show --pretty=fuller
          for try in $(seq 5); do
            git fetch
            git rebase origin/master
            if git push https://x-access-token:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}} master; then
              exit 0
            else
              sleep 3s
            fi
          done
          exit 1
