name: Upload bottles.

on:
  push:
    branches:
      - master
    paths:
      - 'Formula/*'

jobs:
  upload-bottles:
    if: startsWith(github.event.head_commit.message, 'Merge') == false
    runs-on: ubuntu-latest
    container:
      image: homebrew/brew
    steps:
      - name: Get artifact data
        uses: actions/github-script@0.4.0
        id: artifact
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          result-encoding: string
          script: |
            const prs = await github.repos.listPullRequestsAssociatedWithCommit({
              owner: context.repo.owner,
              repo: context.repo.repo,
              commit_sha: context.payload.head_commit.id
            })
            console.log(prs.data.length + " prs")
            if (prs.data.length === 0) {
              console.log("No pull requests are associated with this merge commit.")
              return 0
            }
            const pr = prs.data[0]
            console.log("first pr head ref=" + pr.head.ref)

            // register needed endpoints since the github action is too old
            github.registerEndpoints({
              actions: {
                listWorkflowRuns: {
                  method: "GET",
                  url: "/repos/:owner/:repo/actions/workflows/:workflow_id/runs",
                  headers: {
                    accept: "application/vnd.github.groot-preview+json"
                  },
                  params: {
                    owner: {
                      required: true,
                      type: "string"
                    },
                    repo: {
                      required: true,
                      type: "string"
                    },
                    workflow_id: {
                      required: true,
                      type: "string",
                    },
                    branch: {
                      type: "string",
                    }
                  }
                },
                listWorkflowRunArtifacts: {
                  method: "GET",
                  url: "/repos/:owner/:repo/actions/runs/:run_id/artifacts",
                  headers: {
                    accept: "application/vnd.github.groot-preview+json"
                  },
                  params: {
                    owner: {
                      required: true,
                      type: "string"
                    },
                    repo: {
                      required: true,
                      type: "string"
                    },
                    run_id: {
                      required: true,
                      type: "integer",
                    }
                  }
                }
              }
            });

            const runs = await github.actions.listWorkflowRuns({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: "build-bottles.yml",
              branch: pr.head.ref
              })
            console.log(runs.data.total_count + " runs")
            if (runs.data.total_count === 0) {
              console.log("No workflow runs are associated with this pull request.")
              return 0
            }

            const artifacts = await github.actions.listWorkflowRunArtifacts({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: runs.data.workflow_runs[0].id
              })
            console.log(artifacts.data.total_count + " artifacts")
            if (artifacts.data.total_count === 0) {
              console.log("No artifacts were uploaded for this workflow run.")
              return 0
            }
            console.log("Artifact <" + artifacts.data.artifacts[0].archive_download_url + ">")
            return artifacts.data.artifacts[0].id
      - name: Checkout tap
        if: steps.artifact.outputs.result != 0
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup tap
        if: steps.artifact.outputs.result != 0
        run: |
          rm -rf $(brew --repository ${{github.repository}})
          ln -s $GITHUB_WORKSPACE $(brew --repository ${{github.repository}})
      - name: Setup git
        if: steps.artifact.outputs.result != 0
        run: |
          git config --global user.name BrewTestBot
          git config --global user.email homebrew-test-bot@lists.sfconservancy.org
      - name: Install dependencies
        if: steps.artifact.outputs.result != 0
        run: |
          apt update
          apt install -y unzip
      - name: Upload and publish bottles
        env:
          HOMEBREW_BINTRAY_USER: linuxbrewtestbot
          HOMEBREW_BINTRAY_KEY: ${{secrets.HOMEBREW_BINTRAY_KEY}}
          HOMEBREW_NO_ANALYTICS: 1
          HOMEBREW_NO_AUTO_UPDATE: 1
        if: steps.artifact.outputs.result != 0
        run: |
          set -eu
          mkdir ~/bottles
          cd ~/bottles
          artifact_id=${{steps.artifact.outputs.result}}
          echo "artifact_id=$artifact_id"
          curl -L -o bottles.zip "https://${{secrets.HOMEBREW_GITHUB_API_TOKEN}}@api.github.com/repos/${{github.repository}}/actions/artifacts/$artifact_id/zip"
          file bottles.zip
          unzip bottles.zip
          brew test-bot \
            --tap=homebrew/core \
            --bintray-org=linuxbrew \
            --ci-upload \
            --publish \
            --keep-old
      - name: Push bottle commit
        if: steps.artifact.outputs.result != 0
        run: |
          cd $(brew --repo ${{github.repository}})
          msg=$(git show -s --format=format:%s)
          git commit --amend -m "$msg" -m "Co-authored-by: ${{github.event.pusher.name}} <${{github.event.pusher.email}}>"
          git show
          git fetch
          git rebase origin/master
          git push https://x-access-token:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}} master
